### ISSUE TITLE
vplants.plantgl python import error

### ISSUE THREAD

**Issue by jlegrand62** [openalea/openalea-recipes#53]
Using the following config file to create a conda environment (ubuntu 16.04):
```yaml
name: lineage_editor
channels:
  - openalea
  - defaults
dependencies:
  - python=2.7
  - openalea.sconsx
  - openalea.components
  - vplants.plantgl
  - pyqglviewer
```
I get an error when testing python import:
```python
>>> from vplants.plantgl.all import Scene
Exception Boost.Python.ArgumentError: 'Python argument types in\n    SceneCodec.__del__(AscCodec)\ndid not match C++ signature:\n    __del__(PySceneCodec*)' in <bound method AscCodec.__del__ of <openalea.plantgl.codec.asc.AscCodec object at 0x7fa841ba6368>> ignored
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jonathan/.miniconda2/envs/lineage_editor/lib/python2.7/site-packages/VPlants.PlantGL-2.21.0-py2.7.egg/openalea/plantgl/all.py", line 8, in <module>
    import codec
  File "/home/jonathan/.miniconda2/envs/lineage_editor/lib/python2.7/site-packages/VPlants.PlantGL-2.21.0-py2.7.egg/openalea/plantgl/codec/__init__.py", line 1, in <module>
    import asc
  File "/home/jonathan/.miniconda2/envs/lineage_editor/lib/python2.7/site-packages/VPlants.PlantGL-2.21.0-py2.7.egg/openalea/plantgl/codec/asc.py", line 110, in <module>
    codec = AscCodec()
  File "/home/jonathan/.miniconda2/envs/lineage_editor/lib/python2.7/site-packages/VPlants.PlantGL-2.21.0-py2.7.egg/openalea/plantgl/codec/asc.py", line 16, in __init__
    sg.SceneCodec.__init__(self,"ASC",sg.SceneCodec.Mode.ReadWrite)
Boost.Python.ArgumentError: Python argument types in
    SceneCodec.__init__(AscCodec, str, Mode)
did not match C++ signature:
    __init__(_object*)
    __init__(_object*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > name)
    __init__(_object*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > name, PGL::SceneCodec::Mode mode)
```

**Comment by pradal** [comment]
This error has been fixed. See openalea/plantgl#8
